version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: ./docker/gateway/Dockerfile
    container_name: reward-gateway
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=${PORT_GATEWAY:-3000}
      - AUTH_HOST=auth
      - AUTH_PORT=${PORT_AUTH:-3001}
      - EVENT_HOST=event
      - EVENT_PORT=${PORT_EVENT:-3002}
      - JWT_SECRET=${JWT_SECRET:-verysecretkey123!nexon}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-1d}
    depends_on:
      - auth
      - event
    networks:
      - reward-network
    volumes:
      - ./logs:/app/logs

  auth:
    build:
      context: .
      dockerfile: ./docker/auth/Dockerfile
    container_name: reward-auth
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=${PORT_AUTH:-3001}
      - MONGODB_URI=mongodb://root:root123@mongodb:27017/reward-system?authSource=admin
      - JWT_SECRET=${JWT_SECRET:-verysecretkey123!nexon}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-1d}
    depends_on:
      - mongodb
    networks:
      - reward-network
    volumes:
      - ./logs:/app/logs

  event:
    build:
      context: .
      dockerfile: ./docker/event/Dockerfile
    container_name: reward-event
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=${PORT_EVENT:-3002}
      - MONGODB_URI=mongodb://root:root123@mongodb:27017/reward-system?authSource=admin
      - INNGEST_DEV=${INNGEST_DEV:-true}
      - INNGEST_SIGNING_KEY=${INNGEST_SIGNING_KEY:-dev_inngest_signing_key}
    depends_on:
      - mongodb
    networks:
      - reward-network
    volumes:
      - ./logs:/app/logs

  mongodb:
    image: mongo:5.0
    container_name: reward-mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
      - MONGO_INITDB_DATABASE=reward-system
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - reward-network

networks:
  reward-network:
    driver: bridge

volumes:
  mongodb_data:
